### ISSUE TITLE
Control Pod Mac Address

### ISSUE THREAD

**Issue by alennartz** [Azure/azure-container-networking#1735]
**Component (Azure NPM or Azure CNI):**
Azure CNI

**Describe in detail the feature/behavior/change you'd like to see:**  
Have the ability to control the Mac Address assigned to containers in a pod based on a pod annotation

**Orchestrator(e.g. Kubernetes, Docker):**  
Kubernetes

**Operating System (Linux/Windows):**  
I specifically need Windows but don't see why it shouldn't be done for both

**Anything else you would like to add:**  
The primary motivation for this kind of feature is to support running legacy software that is licensed based on mac address inside of a kubernetes cluster. Calico CNI supports this as documented here: https://projectcalico.docs.tigera.io/networking/pod-mac-address but deploying calico cni on aks with windows nodepools isn't fully working (at least I could not get volumes working)

**Comment by rbtr** [comment]
@alennartz this is an interesting use case, but unlikely something that we will support.  

First, Azure CNI is on the way out in favor of Cilium [[1]](https://techcommunity.microsoft.com/t5/azure-networking-blog/azure-cni-powered-by-cilium-for-azure-kubernetes-service-aks/ba-p/3662341) [[2]](https://isovalent.com/blog/post/azure-cni-cilium/) as the "core" CNI plugin for Kubernetes in Azure. Since Cilium CNI will be responsible for setting up the container network namespace (including assigning the MAC), and Azure IPAM is only responsible for IP address management, this kind of feature request would need to go to them.  
(AzCNI will continue to be used on Windows for some time, but we don't want to add dramatically disparate features between supported OSes.)

However, I don't think it should because, fundamentally, the CNI does not (and should not) know how to talk to Kubernetes itself - it is used _by_ Kubernetes through the CNI contracts and neither component should know any more about the other component than what is declared in that Spec. If the CNI tries to get Pod Metadata, it depends on Kubernetes, and then we have circular dependencies.

**Comment by alennartz** [comment]
Thanks for the information Obviously we don't want to introduce circular dependencies. I also agree on principal in not going wider than the CNI spec (with which I am not familiar so please forgive any foolishness ideas caused by this ignorance).

I'm curious as to your thoughts on this alternative: 

What if the concept of statefulness, as represented in k8s by stateful sets, were incorporated in to the CNI spec. In this scenario I would imagine that just as volumes are currently kept the same, MAC address & perhaps IPs could be preserved for pods controlled by a stateful set once initially provisioned. This would not allow us to control the mac address up front but at least keep it stable once set which would be sufficient to solve the initial use case.

Thanks.
