### ISSUE TITLE
Kubernetes pod containers' DNS suffix has the wrong namespace

### ISSUE THREAD

**Issue by bclau** [Azure/azure-container-networking#245]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**Which release version?**: v1.0.11 (used by acs-engine v0.21.2)

---

**Which component (CNI/IPAM/CNM/CNS)**: CNI

---

**Which Operating System (Linux/Windows)**: Windows

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

10.0.17134.1 (WinBuild.160101.0800)

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

Kubernetes v1.11.2, Docker version 

---

**What happened**:

Currently, on new Kubernetes deployments using acs-engine v0.21.2, the containers' DNS suffixes have an issue. When spawning a pod for the first time in a namespace, the DNS suffix will be set as expected: ``foo.svc.cluster.local``, but when creating a second pod in a different namespace, the DNS suffix will still be ``foo.svc.cluster.local``, and it shouldn't.

---

**What you expected to happen**:

The Containers' DNS suffix should reflect the namespace they are spawned in.

---

**How to reproduce it** (as minimally and precisely as possible):

1. Create a new Kubernetes v1.11 deployment using acs-engine v0.21.2. https://paste.ubuntu.com/p/qcTNh5tKfp/ 
2. Create a Kubernetes namespace: ``kubectl create namespace foo``
3. Create a pod in the namespace: ``kubectl create -n foo -f busybox.yaml`` https://paste.ubuntu.com/p/Y9fWFTNtSk/
4. Check that the DNS suffix is as expected (**foo.svc.cluster.local**): ``kubectl exec -n foo win-busybox -- ipconfig /all``
5. Destroy the pod and namespace: ``kubectl delete ns/foo``
6. Create another, different namespace: ``kubectl create namespace bar``
7. Create another pod, in the new namespace, on the same node the previous one was.
8. Check that the DNS suffix is not **bar**.svc.cluster.local, but **foo**.svc.cluster.local, which is wrong: ``kubectl exec -n bar win-busybox -- ipconfig /all``

---

**Anything else we need to know**:

---

**Comment by bclau** [comment]
@PatrickLang

**Comment by daschott** [comment]
@bclau Which conformance tests is this blocking? The 2 DNS ones, or any other ones?

**Comment by sharmasushant** [comment]
we can make this change in azure cni to add all prefixes... there was a early discussion about this that Kubernetes in windows will handle this the same way they are doing it for Linux (and nto rely on cni). But lets make this change in Azure CNI if it help.. @saiyan86  can you please take this up.

**Comment by daschott** [comment]
@dineshgovindasamy FYI

**Comment by daschott** [comment]
@sharmasushant by Kubernetes on Windows do you mean  https://github.com/kubernetes/kubernetes/pull/67435 or separate work?

**Comment by saiyan86** [comment]
@sharmasushant I'm on it.

**Comment by nagiesek** [comment]
Another bug: Network should not be getting created with a DNS suffix, this overrides the endpoint's dns config. The reason for this issue is when the network is being created, the network takes the namespace of the first service created, and sets this as the dns suffix. When endpoints come from different services/namespaces they take their dns config from network. There is a bug in platform where the endpoint's dns suffix is to be taken on top on the network's dns suffix. Until this is fixed, the network should not have any dns suffix.

- Pod created on namespace "foo", network should not have any dns suffix, endpoints created in this pod/service should have dns suffix "foo.svc.cluster.local"
- Pod created on namespace "bar", network should be the same, and endpoints created in this pod service should have dns suffix "bar.svc.cluster.local" 

Regarding the list of prefixes assert list lets track that as a separate issue.

**Comment by PatrickLang** [comment]
Any updates on this?

**Comment by sharmasushant** [comment]
@PatrickLang  Have done the change.. We are validating it right now. @saiyan86 can add more as we make progress.

**Comment by saiyan86** [comment]
@PatrickLang @sharmasushant The fix is in #254

**Comment by daschott** [comment]
Whoops, I was given the wrong binary, apologies. I tried it out again by building from master and confirm this is fixed.
